version: '3.1'

services:
  db:
    container_name: 'db_postgresql'
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'soerjo'
      POSTGRES_PASSWORD: 'soerjo123'
      POSTGRES_DB: 'bank-sampah'
    volumes:
      - ./db_postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

networks:
  nestjs-network:
